sudo: false
os: linux
compiler: gcc
language: cpp
before_install:
script:
  - ./setup_environment.sh
  - source env.sh
  - cd $HOME
  - python build/leadmocha/test_g4sbs_ci/run_buildtests.py
  - cat logs/*
