sudo: false
os: linux
compiler: gcc
language: cpp
before_install:
script:
  - ./setup_environment.sh
  - source ${HOME}/env.sh
  - travis_wait 30 python build/leadmocha/test_g4sbs_ci/run_buildtests.py build/leadmocha/test_g4sbs_ci/
  - cat logs/*
