sudo: false
os: linux
compiler: gcc
language: cpp
cache:
  directories:
    - $HOME/apps
    - $HOME/fieldmaps
before_install:
script:
  - ./setup_environment.sh
  - source env.sh
  - cd $HOME
  - python builds/leadmocha/test_g4sbs_ci/run_buildtests.py
  - cat logs/*
