sudo: false
os: linux
compiler: gcc
language: cpp
before_install:
script:
  - ls
  - pwd
  - ./setup_environment.sh
  - source env.sh
  - pwd
  - ls
  - echo "Starting the tests"
  - travis_wait 30 python run_buildtests.py travis.conf
  - cat logs/*
